-- 0001_baseline (PostgreSQL) — the full nightlio schema.
--
-- Unlike SQLite (where the legacy bootstrap() owns the baseline), Postgres
-- has no pre-history: this migration bootstraps everything on a fresh
-- database. The translation follows the wire-quirk policy in
-- docs/plans/v0.6.0.md ("PG wire-quirk policy") — the HTTP fixtures are the
-- contract, so SQLite's observable quirks are reproduced on purpose:
--
-- * `INTEGER PRIMARY KEY AUTOINCREMENT` -> `bigint GENERATED BY DEFAULT AS
--   IDENTITY` (BY DEFAULT, not ALWAYS: the migrate-to-postgres import tool
--   inserts explicit ids).
-- * Every text column carries `COLLATE "C"` (byte order), matching SQLite's
--   BINARY collation for name ordering and the lexicographic date
--   MIN/MAX/BETWEEN the fixtures pin.
-- * Timestamp columns are text, defaulted via nightlio_now(), because SQLite
--   CURRENT_TIMESTAMP stores 'YYYY-MM-DD HH:MM:SS' UTC text and that text
--   appears verbatim on the wire.
-- * `mood` is double precision with the same 1..5 CHECK: SQLite's dynamic
--   typing let REAL moods through, and the API serves them as floats.
-- * `nft_minted` is integer DEFAULT 0: SQLite BOOLEAN is just INTEGER, and
--   the wire shows raw 0/1.
-- * nightlio_safe_date() needs pg_input_is_valid — PostgreSQL >= 16 required.
--
-- This file is frozen once shipped: its checksum is recorded in
-- schema_migrations, and the runner refuses to start if it ever changes.

-- Helper functions ------------------------------------------------------------

-- The text SQLite's CURRENT_TIMESTAMP produces: 'YYYY-MM-DD HH:MM:SS' in UTC.
CREATE OR REPLACE FUNCTION nightlio_now() RETURNS text
LANGUAGE sql STABLE
AS $$
    SELECT to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD HH24:MI:SS')
$$;

-- strftime-on-garbage parity: SQLite date functions return NULL on
-- unparseable input instead of erroring. pg_input_is_valid is PostgreSQL 16+.
CREATE OR REPLACE FUNCTION nightlio_safe_date(value text) RETURNS date
LANGUAGE sql STABLE
AS $$
    SELECT CASE
        WHEN value IS NOT NULL AND pg_input_is_valid(value, 'date')
            THEN value::date
        ELSE NULL
    END
$$;

-- Tables (FK order) -----------------------------------------------------------

CREATE TABLE users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_id text COLLATE "C" UNIQUE NOT NULL,
    email text COLLATE "C" NOT NULL,
    name text COLLATE "C" NOT NULL,
    avatar_url text COLLATE "C",
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    last_login text COLLATE "C" DEFAULT nightlio_now(),
    auth_provider text COLLATE "C",
    external_id text COLLATE "C",
    password_hash text COLLATE "C",
    theme_preference text COLLATE "C"
);

CREATE TABLE mood_entries (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    date text COLLATE "C" NOT NULL,
    mood double precision NOT NULL CHECK (mood >= 1 AND mood <= 5),
    content text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    updated_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE groups (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint,
    name text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE group_options (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id bigint NOT NULL,
    name text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE CASCADE
);

CREATE TABLE entry_selections (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entry_id bigint NOT NULL,
    option_id bigint NOT NULL,
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (entry_id) REFERENCES mood_entries (id) ON DELETE CASCADE,
    FOREIGN KEY (option_id) REFERENCES group_options (id) ON DELETE CASCADE
);

CREATE TABLE achievements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    achievement_type text COLLATE "C" NOT NULL,
    earned_at text COLLATE "C" DEFAULT nightlio_now(),
    nft_minted integer DEFAULT 0,
    nft_token_id bigint,
    nft_tx_hash text COLLATE "C",
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    UNIQUE (user_id, achievement_type)
);

CREATE TABLE goals (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    title text COLLATE "C" NOT NULL,
    description text COLLATE "C",
    frequency_per_week bigint NOT NULL CHECK (frequency_per_week >= 1 AND frequency_per_week <= 7),
    completed bigint NOT NULL DEFAULT 0,
    streak bigint NOT NULL DEFAULT 0,
    period_start text COLLATE "C",
    last_completed_date text COLLATE "C",
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    updated_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE goal_completions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    goal_id bigint NOT NULL,
    date text COLLATE "C" NOT NULL,
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (goal_id) REFERENCES goals (id) ON DELETE CASCADE,
    UNIQUE (user_id, goal_id, date)
);

CREATE TABLE user_metrics (
    user_id bigint PRIMARY KEY,
    stats_views bigint NOT NULL DEFAULT 0,
    updated_at text COLLATE "C" DEFAULT nightlio_now(),
    last_view_date text COLLATE "C",
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE TABLE activity_log (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    event_type text COLLATE "C" NOT NULL,
    metadata text COLLATE "C",
    created_at text COLLATE "C" DEFAULT nightlio_now(),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

-- Indexes (every index bootstrap.rs creates, including the UNIQUE ones) -------

CREATE UNIQUE INDEX idx_users_provider_external ON users (auth_provider, external_id);
CREATE UNIQUE INDEX idx_groups_user_name ON groups (user_id, name);
CREATE INDEX idx_mood_entries_date ON mood_entries (date);
CREATE INDEX idx_mood_entries_user_date ON mood_entries (user_id, date);
CREATE INDEX idx_goals_user ON goals (user_id);
CREATE INDEX idx_goal_completions_user_goal ON goal_completions (user_id, goal_id);
CREATE INDEX idx_goal_completions_date ON goal_completions (date);
CREATE INDEX idx_activity_log_user_created ON activity_log (user_id, created_at DESC);
