"""OIDC single sign-on blueprint.

Runs a standard Authorization Code flow against any spec-compliant OpenID
Connect provider (Pocket ID is the recommended self-host option). The
discovery document is derived from ``OIDC_ISSUER_URL``; ``state`` and
``nonce`` are generated by Authlib during ``authorize_redirect`` and
validated in ``authorize_access_token`` (mismatch raises, which we map to a
generic 400). Never log tokens, authorization codes, or identity-provider
responses here.
"""

from urllib.parse import urlsplit

from flask import Blueprint, current_app, jsonify, redirect, request, url_for

# Lazy-load heavy/optional dependencies inside handlers to avoid import errors
# when OIDC is disabled or deps aren't installed.

oauth_bp = Blueprint("oauth", __name__)


def _get_oidc_settings():
    """Return (issuer, client_id, client_secret, callback_url) or None."""
    # Support running as a package (api.*) and from within the api/ directory
    try:
        from api.config import get_config
    except ImportError:  # pragma: no cover - fallback for running from inside api/
        from config import get_config  # type: ignore

    cfg = get_config()
    if not cfg.oidc_enabled or not cfg.OIDC_CLIENT_ID:
        return None
    return (
        cfg.OIDC_ISSUER_URL.rstrip("/"),
        cfg.OIDC_CLIENT_ID,
        cfg.OIDC_CLIENT_SECRET,
        cfg.OIDC_CALLBACK_URL,
    )


def _safe_frontend_base(base: str) -> str:
    """Validate FRONTEND_URL before using it as a redirect target.

    The redirect built from this base carries the SSO token in its URL
    fragment, so an unvalidated base is an open redirect that hands the
    token to whatever origin FRONTEND_URL points at. Only two shapes are
    trusted: a relative path (single leading slash), or an absolute
    http(s) URL whose host matches this request's host. Anything else is
    ignored and the redirect stays on the API origin.
    """
    base = base.rstrip("/")
    if not base:
        return ""
    # Backslashes are treated as slashes by some browsers ("/\evil.com"),
    # so never allow them through.
    if "\\" not in base:
        if base.startswith("/") and not base.startswith("//"):
            # Relative path on the API origin (e.g. behind a shared proxy).
            return base
        parts = urlsplit(base)
        if (
            parts.scheme in ("http", "https")
            and parts.netloc
            and parts.netloc.lower() == request.host.lower()
        ):
            return base
    current_app.logger.warning(
        "Ignoring FRONTEND_URL: not a relative path or same-origin URL"
    )
    return ""


def _frontend_redirect(fragment: str):
    """Redirect the browser back to the SPA login page.

    The callback is a top-level browser navigation, so the token (or an
    error flag) is handed off in the URL fragment — fragments are never
    sent to servers, so the token stays out of access logs. FRONTEND_URL
    covers deployments where the SPA lives on a path or port of the same
    host; empty means same origin as the API. The value is validated by
    _safe_frontend_base before use — an untrusted value falls back to a
    same-origin redirect rather than leaking the fragment off-host.
    """
    # Support running as a package (api.*) and from within the api/ directory
    try:
        from api.config import get_config
    except ImportError:  # pragma: no cover - fallback for running from inside api/
        from config import get_config  # type: ignore

    base = _safe_frontend_base((get_config().FRONTEND_URL or "").strip())
    return redirect(f"{base}/login#{fragment}")


def _register_oidc_client(oauth, issuer, client_id, client_secret):
    oauth.register(
        name="oidc",
        client_id=client_id,
        client_secret=client_secret,
        server_metadata_url=f"{issuer}/.well-known/openid-configuration",
        client_kwargs={"scope": "openid email profile"},
    )
    return oauth.oidc


@oauth_bp.get("/auth/login/oidc")
def login_oidc():
    # Import inside route to keep module import cheap and optional
    try:
        from authlib.integrations.flask_client import OAuth  # type: ignore
    except Exception:
        return jsonify({"error": "OAuth dependencies not installed"}), 503

    settings = _get_oidc_settings()
    if settings is None:
        return jsonify({"error": "OIDC is not configured"}), 404
    issuer, client_id, client_secret, callback_url = settings

    oauth = OAuth(current_app)
    client = _register_oidc_client(oauth, issuer, client_id, client_secret)

    redirect_uri = callback_url or url_for("oauth.oidc_callback", _external=True)
    # authorize_redirect stores state and nonce in the session for the
    # callback to validate.
    return client.authorize_redirect(redirect_uri)


@oauth_bp.get("/auth/callback/oidc")
def oidc_callback():
    try:
        from authlib.integrations.flask_client import OAuth  # type: ignore
    except Exception:
        return jsonify({"error": "OAuth dependencies not installed"}), 503

    settings = _get_oidc_settings()
    if settings is None:
        return jsonify({"error": "OIDC is not configured"}), 404
    issuer, client_id, client_secret, _callback_url = settings

    oauth = OAuth(current_app)
    client = _register_oidc_client(oauth, issuer, client_id, client_secret)

    try:
        # Validates state against the session (mismatch raises) and parses
        # the ID token, validating signature, issuer, audience, expiry, and
        # the nonce stored during authorize_redirect.
        token = client.authorize_access_token()
        userinfo = token.get("userinfo") or client.userinfo(token=token)
    except Exception:
        # Deliberately generic: no codes, tokens, or IDP payloads in logs.
        current_app.logger.warning("OIDC callback failed validation")
        return _frontend_redirect("sso_error=callback_failed")

    subject = userinfo.get("sub")
    if not subject:
        return _frontend_redirect("sso_error=callback_failed")
    email = userinfo.get("email")
    name = userinfo.get("name") or userinfo.get("preferred_username")
    avatar = userinfo.get("picture")

    user_service = current_app.extensions.get("user_service")  # type: ignore[attr-defined]
    if user_service is None:
        return jsonify({"error": "User service unavailable"}), 500

    try:
        user = user_service.handle_oidc_login(subject, email, name, avatar)
    except Exception:
        current_app.logger.error("OIDC user provisioning failed")
        return _frontend_redirect("sso_error=auth_failed")
    if not user:
        return _frontend_redirect("sso_error=auth_failed")

    # Issue JWT using existing app config (legacy)
    try:
        from jose import jwt  # type: ignore
        from datetime import datetime, timedelta, timezone

        payload = {
            "user_id": user["id"],
            "exp": datetime.now(timezone.utc)
            + timedelta(seconds=current_app.config["JWT_ACCESS_TOKEN_EXPIRES"]),
            "iat": datetime.now(timezone.utc),
        }
        app_token = jwt.encode(
            payload, current_app.config["JWT_SECRET_KEY"], algorithm="HS256"
        )
    except Exception:
        return _frontend_redirect("sso_error=auth_failed")

    # Hand the token to the SPA in the URL fragment; the frontend stores it
    # in localStorage (AuthContext) and strips the fragment -- this is the
    # immediate-state path, used before the page has even finished loading.
    # The same token is ALSO set as the httpOnly session cookie below, which
    # is what persists the session going forward (e.g. after localStorage is
    # cleared, or once the frontend stops relying on localStorage entirely).
    try:
        from api.utils.auth_cookies import set_auth_cookie
    except ImportError:  # pragma: no cover - fallback for running from inside api/
        from utils.auth_cookies import set_auth_cookie  # type: ignore

    response = _frontend_redirect(f"sso_token={app_token}")
    set_auth_cookie(
        response, app_token, current_app.config["JWT_ACCESS_TOKEN_EXPIRES"]
    )
    return response
