//! PostgreSQL twin of `db/users.rs` (the `UsersMixin` port). Same operation
//! set, same parameters, same rows on the wire — translated statement by
//! statement per the wire-quirk policy in docs/plans/v0.6.0.md:
//!
//! - `?` placeholders become `$n`; `last_insert_rowid()` sites become
//!   `RETURNING id` (identity columns are `GENERATED BY DEFAULT`).
//! - `CURRENT_TIMESTAMP` becomes `nightlio_now()` — the baseline SQL
//!   function emitting the same `YYYY-MM-DD HH:MM:SS` UTC text SQLite
//!   stores, verbatim on the wire.
//! - The NOT-NULL-before-ON-CONFLICT quirk carries over natively: like
//!   SQLite, PostgreSQL checks NOT NULL on the proposed row before conflict
//!   resolution, so `upsert_user_by_google_id` with a NULL email fails even
//!   when the row exists and DO UPDATE would have COALESCEd (verified
//!   against a live PostgreSQL 16 on 2026-08-22). The identity sequence
//!   burns a value on every conflicting insert attempt, matching the
//!   AUTOINCREMENT id burn the fixtures document.
//! - Python-truthiness create-path defaults (`email or default`) are the
//!   same Rust helpers, unchanged.
//!
//! Twins take `&impl GenericClient` (`&mut` when they open a transaction)
//! so store ops can run several steps on one checked-out connection.

use tokio_postgres::GenericClient;

use crate::db::DatabaseError;
use crate::db::pg::util;
use crate::db::users::{UserRow, compat_google_id};

// --- SQL (dialect-translated from `db/users.rs` / `common::sql_queries`) -----

const GET_USER_BY_GOOGLE_ID_SQL: &str = "SELECT id, google_id, email, name, avatar_url, \
     auth_provider, external_id, created_at, last_login FROM users WHERE google_id = $1";

const GET_USER_BY_ID_SQL: &str = "SELECT id, google_id, email, name, avatar_url, \
     auth_provider, external_id, created_at, last_login FROM users WHERE id = $1";

const GET_USER_BY_PROVIDER_SQL: &str = "SELECT id, google_id, email, name, avatar_url, \
     auth_provider, external_id, created_at, last_login FROM users \
     WHERE auth_provider = $1 AND external_id = $2";

const CREATE_USER_SQL: &str =
    "INSERT INTO users (google_id, email, name, avatar_url) VALUES ($1, $2, $3, $4) RETURNING id";

const CREATE_PROVIDER_USER_SQL: &str = "INSERT INTO users (google_id, email, name, avatar_url, \
     auth_provider, external_id, password_hash) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id";

/// `UPSERT_USER` + the RETURNING suffix, with `CURRENT_TIMESTAMP` →
/// `nightlio_now()`.
const UPSERT_USER_SQL: &str = "INSERT INTO users (google_id, email, name, avatar_url) \
     VALUES ($1, $2, $3, $4) \
     ON CONFLICT (google_id) DO UPDATE SET \
       email=COALESCE(excluded.email, users.email), \
       name=COALESCE(excluded.name, users.name), \
       avatar_url=COALESCE(excluded.avatar_url, users.avatar_url), \
       last_login=nightlio_now() \
     RETURNING id, google_id, email, name, avatar_url, \
       auth_provider, external_id, created_at, last_login";

const UPDATE_USER_LAST_LOGIN_SQL: &str =
    "UPDATE users SET last_login = nightlio_now() WHERE id = $1";

const UPDATE_OIDC_USER_SQL: &str = "UPDATE users \
        SET email = COALESCE($1, email), \
            name = COALESCE($2, name), \
            avatar_url = COALESCE($3, avatar_url), \
            last_login = nightlio_now() \
      WHERE id = $4";

const GET_USER_THEME_SQL: &str = "SELECT theme_preference FROM users WHERE id = $1";

const SET_USER_THEME_SQL: &str = "UPDATE users SET theme_preference = $1 WHERE id = $2";

const GET_USER_PASSWORD_HASH_SQL: &str = "SELECT password_hash FROM users WHERE id = $1";

const SET_USER_PASSWORD_SQL: &str = "UPDATE users SET password_hash = $1 WHERE id = $2";

/// Map a row from any query SELECTing the shared 9-column list in order.
fn user_from_row(row: &tokio_postgres::Row) -> UserRow {
    UserRow {
        id: row.get(0),
        google_id: row.get(1),
        email: row.get(2),
        name: row.get(3),
        avatar_url: row.get(4),
        auth_provider: row.get(5),
        external_id: row.get(6),
        created_at: row.get(7),
        last_login: row.get(8),
    }
}

/// Python truthiness for create-path string defaults (`email or default`):
/// `None` and `""` both count as missing — same rule as the SQLite twin.
fn non_empty(value: Option<&str>) -> Option<&str> {
    value.filter(|s| !s.is_empty())
}

/// Twin of `users::create_user`: plain INSERT, new id via RETURNING.
pub async fn create_user(
    client: &impl GenericClient,
    google_id: &str,
    email: &str,
    name: &str,
    avatar_url: Option<&str>,
) -> Result<i64, DatabaseError> {
    let row = client
        .query_one(CREATE_USER_SQL, &[&google_id, &email, &name, &avatar_url])
        .await
        .map_err(util::db_error)?;
    Ok(row.get(0))
}

/// Twin of `users::get_user_by_google_id`.
pub async fn get_user_by_google_id(
    client: &impl GenericClient,
    google_id: &str,
) -> Result<Option<UserRow>, DatabaseError> {
    let row = client
        .query_opt(GET_USER_BY_GOOGLE_ID_SQL, &[&google_id])
        .await
        .map_err(util::db_error)?;
    Ok(row.as_ref().map(user_from_row))
}

/// Twin of `users::get_user_by_id`.
pub async fn get_user_by_id(
    client: &impl GenericClient,
    user_id: i64,
) -> Result<Option<UserRow>, DatabaseError> {
    let row = client
        .query_opt(GET_USER_BY_ID_SQL, &[&user_id])
        .await
        .map_err(util::db_error)?;
    Ok(row.as_ref().map(user_from_row))
}

/// Twin of `users::get_user_by_provider`.
pub async fn get_user_by_provider(
    client: &impl GenericClient,
    auth_provider: &str,
    external_id: &str,
) -> Result<Option<UserRow>, DatabaseError> {
    let row = client
        .query_opt(GET_USER_BY_PROVIDER_SQL, &[&auth_provider, &external_id])
        .await
        .map_err(util::db_error)?;
    Ok(row.as_ref().map(user_from_row))
}

/// Twin of `users::get_user_theme` — same bug-compatible flattening:
/// `None` for both a missing user and a NULL `theme_preference`.
pub async fn get_user_theme(
    client: &impl GenericClient,
    user_id: i64,
) -> Result<Option<String>, DatabaseError> {
    let row = client
        .query_opt(GET_USER_THEME_SQL, &[&user_id])
        .await
        .map_err(util::db_error)?;
    Ok(row.and_then(|row| row.get::<_, Option<String>>(0)))
}

/// Twin of `users::set_user_theme` — silent no-op for unknown ids.
pub async fn set_user_theme(
    client: &impl GenericClient,
    user_id: i64,
    theme: &str,
) -> Result<(), DatabaseError> {
    client
        .execute(SET_USER_THEME_SQL, &[&theme, &user_id])
        .await
        .map_err(util::db_error)?;
    Ok(())
}

/// Twin of `users::update_user_last_login`.
pub async fn update_user_last_login(
    client: &impl GenericClient,
    user_id: i64,
) -> Result<(), DatabaseError> {
    client
        .execute(UPDATE_USER_LAST_LOGIN_SQL, &[&user_id])
        .await
        .map_err(util::db_error)?;
    Ok(())
}

/// Twin of `users::upsert_user_by_google_id`: single-statement upsert with
/// RETURNING (atomic on its own — the SQLite twin's explicit transaction
/// wrapped exactly this one statement).
pub async fn upsert_user_by_google_id(
    client: &impl GenericClient,
    google_id: &str,
    email: Option<&str>,
    name: Option<&str>,
    avatar_url: Option<&str>,
) -> Result<Option<UserRow>, DatabaseError> {
    let row = client
        .query_opt(UPSERT_USER_SQL, &[&google_id, &email, &name, &avatar_url])
        .await
        .map_err(util::db_error)?;
    Ok(row.as_ref().map(user_from_row))
}

/// Twin of `users::upsert_oidc_user`: select-then-insert/update inside one
/// transaction (not ON CONFLICT — the row is covered by two unique
/// constraints and upsert conflict targets only handle one).
pub async fn upsert_oidc_user(
    client: &mut impl GenericClient,
    external_id: &str,
    email: Option<&str>,
    name: Option<&str>,
    avatar_url: Option<&str>,
    provider: &str,
) -> Result<Option<UserRow>, DatabaseError> {
    let tx = client.transaction().await.map_err(util::db_error)?;

    let existing: Option<i64> = tx
        .query_opt(
            "SELECT id FROM users WHERE auth_provider = $1 AND external_id = $2",
            &[&provider, &external_id],
        )
        .await
        .map_err(util::db_error)?
        .map(|row| row.get(0));

    let user_id = match existing {
        Some(id) => {
            tx.execute(UPDATE_OIDC_USER_SQL, &[&email, &name, &avatar_url, &id])
                .await
                .map_err(util::db_error)?;
            id
        }
        None => {
            // Python: `email or f"{external_id}@{provider}.invalid"`,
            // `name or "User"` — empty strings count as missing.
            let email = non_empty(email)
                .map(str::to_owned)
                .unwrap_or_else(|| format!("{external_id}@{provider}.invalid"));
            let name = non_empty(name).unwrap_or("User");
            let row = tx
                .query_one(
                    CREATE_PROVIDER_USER_SQL,
                    &[
                        &compat_google_id(provider, external_id),
                        &email,
                        &name,
                        &avatar_url,
                        &provider,
                        &external_id,
                        &Option::<String>::None,
                    ],
                )
                .await
                .map_err(util::db_error)?;
            row.get(0)
        }
    };

    let row = tx
        .query_opt(GET_USER_BY_ID_SQL, &[&user_id])
        .await
        .map_err(util::db_error)?;
    tx.commit().await.map_err(util::db_error)?;
    Ok(row.as_ref().map(user_from_row))
}

/// Twin of `users::create_local_user`. Returns `Ok(None)` on an integrity
/// violation (duplicate username — the UNIQUE `(auth_provider, external_id)`
/// index), which the store arm maps to the route's 409 exactly like the
/// SQLite arm's `is_integrity_error` match.
pub async fn create_local_user(
    client: &impl GenericClient,
    username: &str,
    password_hash: &str,
    email: Option<&str>,
    name: Option<&str>,
) -> Result<Option<i64>, DatabaseError> {
    let email = non_empty(email)
        .map(str::to_owned)
        .unwrap_or_else(|| format!("{username}@localhost"));
    let name = non_empty(name).unwrap_or(username);
    match client
        .query_one(
            CREATE_PROVIDER_USER_SQL,
            &[
                &compat_google_id("local", username),
                &email,
                &name,
                &Option::<String>::None,
                &"local",
                &username,
                &password_hash,
            ],
        )
        .await
    {
        Ok(row) => Ok(Some(row.get(0))),
        Err(exc) if util::is_integrity_violation(&exc) => Ok(None),
        Err(exc) => Err(util::db_error(exc)),
    }
}

/// Twin of `users::get_user_password_hash` — same flattening as
/// [`get_user_theme`].
pub async fn get_user_password_hash(
    client: &impl GenericClient,
    user_id: i64,
) -> Result<Option<String>, DatabaseError> {
    let row = client
        .query_opt(GET_USER_PASSWORD_HASH_SQL, &[&user_id])
        .await
        .map_err(util::db_error)?;
    Ok(row.and_then(|row| row.get::<_, Option<String>>(0)))
}

/// Twin of `users::set_user_password` — silent no-op for unknown ids.
pub async fn set_user_password(
    client: &impl GenericClient,
    user_id: i64,
    password_hash: &str,
) -> Result<(), DatabaseError> {
    client
        .execute(SET_USER_PASSWORD_SQL, &[&password_hash, &user_id])
        .await
        .map_err(util::db_error)?;
    Ok(())
}

#[cfg(test)]
mod tests {
    //! Live-PG quirk tests (skipped unless `NIGHTLIO_PG_TEST_URL` is set).
    //! Expected values mirror the SQLite twin's pinned-from-Python tests in
    //! `db/users.rs` — the wire rows must match across backends.

    use super::*;
    use crate::db::pg::util::test_support::{connect_scratch, seed_default_user};

    /// `nightlio_now()` produces `YYYY-MM-DD HH:MM:SS`, like SQLite's
    /// CURRENT_TIMESTAMP.
    fn assert_timestampish(value: &Option<String>) {
        let v = value.as_deref().expect("timestamp column must be set");
        assert_eq!(v.len(), 19, "unexpected timestamp shape: {v}");
        assert_eq!(&v[4..5], "-");
        assert_eq!(&v[10..11], " ");
    }

    #[tokio::test]
    async fn upsert_by_google_id_inserts_updates_and_keeps_the_null_email_quirk() {
        let Some(client) = connect_scratch("ws4a_users_upsert").await else {
            return;
        };
        let row = upsert_user_by_google_id(
            &client,
            "g-123",
            Some("a@b.c"),
            Some("Alice"),
            Some("http://old-avatar"),
        )
        .await
        .unwrap()
        .expect("insert path returns the row");
        assert_eq!(row.email, "a@b.c");
        assert_eq!(row.name, "Alice");
        assert_eq!(row.avatar_url.as_deref(), Some("http://old-avatar"));
        assert_eq!(row.auth_provider, None);
        assert_timestampish(&row.created_at);
        assert_timestampish(&row.last_login);
        let created_id = row.id;

        // Update path: email/name replaced, avatar kept via COALESCE.
        client
            .execute(
                "UPDATE users SET last_login='2020-01-01 00:00:00' WHERE google_id='g-123'",
                &[],
            )
            .await
            .unwrap();
        let row = upsert_user_by_google_id(&client, "g-123", Some("new@b.c"), Some("Alice2"), None)
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.id, created_id, "update path must not create a row");
        assert_eq!(row.email, "new@b.c");
        assert_eq!(row.name, "Alice2");
        assert_eq!(row.avatar_url.as_deref(), Some("http://old-avatar"));
        assert_ne!(row.last_login.as_deref(), Some("2020-01-01 00:00:00"));

        // Quirk: NULL email fails NOT NULL before conflict resolution even
        // on an existing row, and the row stays untouched (same observable
        // behavior as SQLite's IntegrityError + rollback).
        let err = upsert_user_by_google_id(&client, "g-123", None, Some("X"), None)
            .await
            .unwrap_err();
        assert!(
            err.to_string().contains("not-null constraint"),
            "unexpected error: {err}"
        );
        let row = get_user_by_google_id(&client, "g-123")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.name, "Alice2", "failed upsert must leave the row");

        // The failed attempt and the conflict both burn identity values —
        // the id-burn behavior the fixtures document for SQLite.
        let next = create_user(&client, "g-plain", "p@q.r", "Plain", None)
            .await
            .unwrap();
        assert!(next > created_id + 1, "identity must burn on conflicts");
    }

    #[tokio::test]
    async fn oidc_upsert_creates_with_python_defaults_then_updates() {
        let Some(mut client) = connect_scratch("ws4a_users_oidc").await else {
            return;
        };
        let row = upsert_oidc_user(&mut client, "ext-1", None, None, None, "oidc")
            .await
            .unwrap()
            .expect("create path returns the row");
        assert_eq!(row.google_id, "oidc:ext-1");
        assert_eq!(row.email, "ext-1@oidc.invalid");
        assert_eq!(row.name, "User");
        assert_eq!(row.avatar_url, None);
        assert_eq!(row.auth_provider.as_deref(), Some("oidc"));
        assert_eq!(row.external_id.as_deref(), Some("ext-1"));
        let created_id = row.id;

        let row = upsert_oidc_user(
            &mut client,
            "ext-1",
            Some("o@e.x"),
            None,
            Some("http://av"),
            "oidc",
        )
        .await
        .unwrap()
        .unwrap();
        assert_eq!(row.id, created_id);
        assert_eq!(row.email, "o@e.x");
        assert_eq!(row.name, "User", "COALESCE keeps the stored name");
        assert_eq!(row.avatar_url.as_deref(), Some("http://av"));

        // Provider-scoped lookup finds it; other provider does not.
        let found = get_user_by_provider(&client, "oidc", "ext-1")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(found, row);
        assert_eq!(
            get_user_by_provider(&client, "local", "ext-1")
                .await
                .unwrap(),
            None
        );

        // Empty strings count as missing on the create path (Python `or`).
        let row = upsert_oidc_user(&mut client, "ext-2", Some(""), Some(""), None, "oidc")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.email, "ext-2@oidc.invalid");
        assert_eq!(row.name, "User");
    }

    #[tokio::test]
    async fn local_user_defaults_duplicates_theme_and_password_flattening() {
        let Some(client) = connect_scratch("ws4a_users_local").await else {
            return;
        };
        let default_id = seed_default_user(&client).await;

        let id = create_local_user(&client, "bob", "hash1", None, None)
            .await
            .unwrap()
            .expect("fresh username inserts");
        let row = get_user_by_provider(&client, "local", "bob")
            .await
            .unwrap()
            .unwrap();
        assert_eq!(row.id, id);
        assert_eq!(row.google_id, "local:bob");
        assert_eq!(row.email, "bob@localhost");
        assert_eq!(row.name, "bob");
        assert_eq!(
            get_user_password_hash(&client, id)
                .await
                .unwrap()
                .as_deref(),
            Some("hash1")
        );

        // Explicit email/name used as-is; empty strings fall back.
        let id3 = create_local_user(&client, "dave", "h", Some(""), Some(""))
            .await
            .unwrap()
            .unwrap();
        let row3 = get_user_by_id(&client, id3).await.unwrap().unwrap();
        assert_eq!(row3.email, "dave@localhost");
        assert_eq!(row3.name, "dave");

        // Duplicate username → integrity violation → None (the 409 path).
        assert_eq!(
            create_local_user(&client, "bob", "hash2", None, None)
                .await
                .unwrap(),
            None
        );

        // Theme/password flattening: missing user and NULL both None.
        assert_eq!(get_user_theme(&client, default_id).await.unwrap(), None);
        assert_eq!(get_user_theme(&client, 9999).await.unwrap(), None);
        set_user_theme(&client, default_id, "synthwave")
            .await
            .unwrap();
        assert_eq!(
            get_user_theme(&client, default_id)
                .await
                .unwrap()
                .as_deref(),
            Some("synthwave")
        );
        set_user_theme(&client, 9999, "dark").await.unwrap();
        assert_eq!(get_user_password_hash(&client, 9999).await.unwrap(), None);
        assert_eq!(
            get_user_password_hash(&client, default_id).await.unwrap(),
            None
        );
        set_user_password(&client, id, "hash2").await.unwrap();
        assert_eq!(
            get_user_password_hash(&client, id)
                .await
                .unwrap()
                .as_deref(),
            Some("hash2")
        );

        // update_user_last_login touches the timestamp text.
        client
            .execute(
                "UPDATE users SET last_login='2020-01-01 00:00:00' WHERE id=$1",
                &[&default_id],
            )
            .await
            .unwrap();
        update_user_last_login(&client, default_id).await.unwrap();
        let row = get_user_by_id(&client, default_id).await.unwrap().unwrap();
        assert_ne!(row.last_login.as_deref(), Some("2020-01-01 00:00:00"));
        assert_timestampish(&row.last_login);
    }
}
